#pragma once

// Resource identifiers for the Win32 front end.
// 1 is reserved for the application manifest (CREATEPROCESS_MANIFEST_RESOURCE_ID).

// Main window child controls.
#define IDC_TIMELINES_LIST 1001
#define IDC_TIMELINE_VIEW  1002

// Add Account dialog.
#define IDD_ADD_ACCOUNT    200
#define IDC_PLATFORM_COMBO 201
#define IDC_SERVICE_EDIT   202
#define IDC_HANDLE_EDIT    203
#define IDC_APPPASS_EDIT   204
#define IDC_SERVICE_LABEL  205
#define IDC_HANDLE_LABEL   206
#define IDC_APPPASS_LABEL  207

// Compose dialog.
#define IDD_COMPOSE            220
#define IDC_COMPOSE_CONTEXT    221
#define IDC_COMPOSE_EDIT       222
#define IDC_COMPOSE_CW_LABEL   223
#define IDC_COMPOSE_CW         224
#define IDC_COMPOSE_POST_LABEL 225
#define IDC_COMPOSE_VIS_LABEL  226
#define IDC_COMPOSE_VISIBILITY 227
#define IDC_COMPOSE_LANG_LABEL 228
#define IDC_COMPOSE_LANGUAGE   229
#define IDC_COMPOSE_POLL       230
#define IDC_COMPOSE_POLL_OPT1  231
#define IDC_COMPOSE_POLL_OPT2  232
#define IDC_COMPOSE_POLL_OPT3  233
#define IDC_COMPOSE_POLL_OPT4  234
#define IDC_COMPOSE_POLL_MULTI 235
#define IDC_COMPOSE_DUR_LABEL  236
#define IDC_COMPOSE_DURATION   237
#define IDC_COMPOSE_SCHEDULE   238
#define IDC_COMPOSE_SCHED_TIME 239
#define IDC_COMPOSE_COUNTER    250

// New Timeline dialog.
#define IDD_NEW_TIMELINE   240
#define IDC_TIMELINE_TYPE  241

// Settings property sheet pages.
#define IDD_SET_GENERAL     300
#define IDC_SET_CMDRETURN   301
#define IDD_SET_TIMELINES   310
#define IDC_SET_CACHELIMIT  311
#define IDC_SET_CACHELIMIT_SPIN 312
#define IDC_SET_AUTOREFRESH 313
#define IDC_SET_STREAMING   314
#define IDD_SET_AUDIO       320
#define IDC_SET_SOUNDS      321
#define IDC_SET_SOUNDPACK   322
#define IDC_SET_OPENPACKS   323
#define IDD_SET_SPEECH      330
#define IDC_SET_SPEECH_LIST 331
#define IDC_SET_SPEECH_UP   332
#define IDC_SET_SPEECH_DOWN 333
#define IDD_SET_ADVANCED    340
#define IDC_SET_FETCHPAGES  341
#define IDC_SET_FETCHPAGES_SPIN 342
#define IDD_SET_CONFIRM     350
#define IDC_SET_CONFIRM_BOOST 351
#define IDC_SET_CONFIRM_FAV   352
#define IDC_SET_CONFIRM_CLEAR 353

// Post Info dialog.
#define IDD_POST_INFO         360
#define IDC_POSTINFO_TEXT     361
#define IDC_POSTINFO_REPLY    362
#define IDC_POSTINFO_BOOST    363
#define IDC_POSTINFO_FAVORITE 364
#define IDC_POSTINFO_QUOTE    365
#define IDC_POSTINFO_BROWSER  366
#define IDC_POSTINFO_THREAD   367
